{% set data = load_setup_py_data() %}

package:
  name: ddpw
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - git
    - {{ mpi }}
  run:
    - numpy >=1.21
    - pytorch >=1.10
    - tensorboard >=1.15
    - submitit >=1.2

about:
  home: http://ddpw.projects-tvs.surge.sh
  summary:  A utility package to encapsulate the scaffolding for PyTorch's
            Distributed Data Parallel
  description: The Distributed Data Parallel wrapper (DDPW) is created as a
            utility package to encapsulate the scaffolding for PyTorch's
            Distributed Data Parallel.
